### ISSUE TITLE
不兼容 ASF 6.0.0.3 版本

### ISSUE THREAD

**Issue by HUBBLEEEEEE** [DevSplash/ASFAutoClaimStickers#2]
2024-03-10 11:04:30|dotnet-4042107|ERROR|ASF|InitPlugins() 因发生此错误而失败：AutoClaimStickers, Version=1.0.1.2, Culture=neutral, PublicKeyToken=null
2024-03-10 11:04:30|dotnet-4042107|ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'OnASFInit' in type 'AutoClaimStickers.AutoClaimStickers' from assembly 'AutoClaimStickers, Version=1.0.1.2, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
System.TypeLoadException: Method 'OnASFInit' in type 'AutoClaimStickers.AutoClaimStickers' from assembly 'AutoClaimStickers, Version=1.0.1.2, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2024-03-10 11:04:40|dotnet-4042107|ERROR|ASF|Exit() 正在以 1 错误代码退出！

**Comment by DevSplash** [comment]
Closed by 9b921d032f07cd341faf9c999c3a0d101d6cf730
